image:
  repository: us-central1-docker.pkg.dev/harsha-503911/nginx-repo/nginx-app
  tag: latest
  pullPolicy: IfNotPresent

application:
  enabled: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
