image:
  repository: us-central1-docker.pkg.dev/harsha-gcp-505210/repo-1/nginx-app:v1
  tag: v1
  pullPolicy: IfNotPresent

application:
  enabled: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
