---
# Source: nginx-helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-prod
spec:
  type: LoadBalancer
  selector:
    app: nginx-prod
  ports:
  - port: 80
    targetPort: 80

---
# Source: nginx-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx
        image: "nginx:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
