kapiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-qa
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://github.com/goshh77/helm-gitops.git
      targetRevision: main
      path: charts/nginx
      helm:
        releaseName: nginx-qa
        valueFiles:
          - $values/environments/qa/values.yaml

    - repoURL: https://github.com/goshh77/helm-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
