apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password
  namespace: default
spec:
  refreshInterval: 1m

  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore

  target:
    name: db-secret
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: db-username

    - secretKey: password
      remoteRef:
        key: db-password
