apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config

data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      location /dev {
        rewrite ^/dev/?(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
      }

      location /qa {
        rewrite ^/qa/?(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
      }

      location / {
        try_files $uri $uri/ /index.html;
      }
    }
